pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
    stages {
        stage('Build') {
            steps {
                sh 'make'
            }
        }
        stage('Test'){
            steps {
                sh 'make check'
                junit 'reports/**/*.xml'
            }
        }
        stage('Deploy') {
            steps {
                sh 'make publish'
            }
        }
    }
}

/*
node {
    stage('Build') {
            echo 'Build Stage - Using scripted pipeline..'
    }
    
    stage('Test') {
        echo 'Test Stage- Using scripted pipeline..'
    }
    
    stage('Deploy') {
        echo 'Deploy Stage - Using scripted pipeline..'
    }
}
*/
